channels:
- conda-forge
dependencies:
- pip:
  - flit
- pyyaml
- pip
- ipython
- flit-core<4,>=2
- platformdirs
- packaging
- python>=3.8
- mypy
- types-PyYAML
- black
- pytest
- typeguard
- tqdm
name: beni
